export const CROWDFUNDING_BANNER_HEIGHT_IN_PX = 30;
export const HEADER_HEIGHT_IN_PX = 80;
export const MOBILE_HEADER_LINKS_HEIGHT_IN_PX = 55;

export const TOTAL_DESKTOP_HEADER_HEIGHT_IN_PX =
  CROWDFUNDING_BANNER_HEIGHT_IN_PX + HEADER_HEIGHT_IN_PX;

export const TOTAL_MOBILE_HEADER_HEIGHT_IN_PX =
  CROWDFUNDING_BANNER_HEIGHT_IN_PX + HEADER_HEIGHT_IN_PX + MOBILE_HEADER_LINKS_HEIGHT_IN_PX;
